config/routes.rb
Test1::Application.routes.draw do
  root "static_pages#home"

  resources :options

  resources :pools

  resources :questions

  

end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to 	:question
	validates	:text, presence: true
	validates	:question_id,	presence: true
end

app/models/pool.rb
class Pool < ActiveRecord::Base
	has_many	:question_pools
	has_many	:questions, through: :question_pools
	validates	:name,	presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many 	:pools, through: :question_pools
	has_many	:question_pools
	has_many	:options
	accepts_nested_attributes_for	:pools
	validates	:content,	presence: true
end

app/models/question_pool.rb
class QuestionPool < ActiveRecord::Base
	belongs_to	:question
	belongs_to	:pool
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all.order(:question_id)
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render action: 'show', status: :created, location: @option }
      else
        format.html { render action: 'new' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:question_id, :text, :correct)
    end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /pools
  # GET /pools.json
  def index
    @pools = Pool.all
  end

  # GET /pools/1
  # GET /pools/1.json
  def show
  end

  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # GET /pools/1/edit
  def edit
  end

  # POST /pools
  # POST /pools.json
  def create
    @pool = Pool.new(pool_params)

    respond_to do |format|
      if @pool.save
        format.html { redirect_to @pool, notice: 'Pool was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pool }
      else
        format.html { render action: 'new' }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: 'Pool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to pools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_params
      params.require(:pool).permit(:name)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show

  end

  # GET /questions/new
  def new
  
    @pools = Pool.all
    @question = Question.new
  
  end

  # GET /questions/1/edit
  def edit
    @pools = Pool.all
    @options = Option.where(question_id: params[:id])
    @used_pools = QuestionPool.where(question_id: params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    
    

    respond_to do |format|
      if @question.save
        qid = @question.id
        unless params[:pool].nil? 
          new_pools = params[:pool].each.map(&:to_i)
          new_pools.each do |pool|
            QuestionPool.find_or_create_by(question_id: qid, pool_id: pool)
          end
        end

        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      #if @question.update(question_params)
    current_pools = Question.find(params[:id]).pools.pluck(:id)
    logger.info "----- current pools ---" + current_pools.to_s
    unless params[:pool].nil?
    new_pools = params[:pool].each.map(&:to_i)
    else new_pools = []
    end

    logger.info "----- new pools ---" + new_pools.to_s
    candidate_del = current_pools - new_pools
    logger.info candidate_del
    candidate_add = new_pools - current_pools    
    
    candidate_del.each do |pool|
      logger.info "------------------Processing the request..."
      QuestionPool.where(question_id: params[:id], pool_id: pool).destroy_all

    end

    candidate_add.each do |pool|
      QuestionPool.find_or_create_by(question_id: params[:id], pool_id: pool)
    end

    
      
        #if @question.pools.update(params[:pool].keys,params.values)
        if true
                  format.html { render action: 'show' }
        #format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Тестирование</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
    </div>
    <div class="span10">

<div class="masthead">
<ul class="nav nav-pills pull-right">

  <li class="dropdown">
    <a class="dropdown-toggle"
       data-toggle="dropdown"
       href="<%= questions_path %>">
        Вопросы
       <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
    	<li><a href="<%= questions_path %>">Список</a></li>
       	<li><a href="<%= new_question_path %>">Создать</a></li>
       	<!-- links -->
    </ul>
  </li>


	<!-- OPTIONS -->
  <li class="dropdown">
    <a class="dropdown-toggle"
       data-toggle="dropdown"
       href="<%= options_path %>">
        Ответы
       <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
    	<li><a href="<%= options_path %>">Список</a></li>
       	<li><a href="<%= new_option_path %>">Создать</a></li>
       	<!-- links -->
    </ul>
  </li>


   <li><a href="#">Сиськи</a></li>
</ul>
 <h3 class="muted">Тестирование</h3>
</div>

<hr>

<%= yield %>
<%= debug(params) %>
<%= debug(@pools) %>
    </div>
  </div>
</div>

</body>
</html>

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    
    <%= f.label :quesion_id, 'Для какого вопроса данный ответ' %>
    <%= f.collection_select :question_id, Question.all, :id, :content %>
  </div>  

  <div class="field">

 
    <%= f.label :text, 'Введите текст ответа' %>
    <%= f.text_area :text, size: '80x5' %>
  </div>
  <div class="field">
    <h4> Отмечаем если ответ правильный </h4>
    <%= f.label :correct do %>
    <a href="#" class="btn btn-success btn-mini disabled"><i class="icon-white icon-ok"></i></a> <%= f.check_box :correct %> Этот ответ правильный 
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<h1>Список вариантов ответов</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Question</th>
      <th>Text</th>
      <th>Correct</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <%= raw('<tr><td colspan="6"><p></p></td></tr>') if option.question.id != @old %>
      <tr>
        <td><span class="badge badge-info"><%= option.question_id %></span></td>
        <td><%= option.text %></td>
        <td><%= raw('<a href="#" class="btn btn-success btn-mini disabled"><i class="icon-white icon-ok"></i></a>') if option.correct %></td>
        <td><%= link_to 'Показать', option %></td>
        <td><%= link_to 'Редактировать', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Точно удалить?' } %></td>
        <% @old = option.question_id %>
      </tr>
      <tr></tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>Новый вариант ответа</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @option.question_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @option.text %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @option.correct %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>

app/views/pools/_form.html.erb
<%= form_for(@pool) do |f| %>
  <% if @pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pool.errors.count, "error") %> prohibited this pool from being saved:</h2>

      <ul>
      <% @pool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pools/edit.html.erb
<h1>Editing pool</h1>

<%= render 'form' %>

<%= link_to 'Show', @pool %> |
<%= link_to 'Back', pools_path %>

app/views/pools/index.html.erb
<h1>Listing pools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pools.each do |pool| %>
      <tr>
        <td><%= pool.name %></td>
        <td><%= link_to 'Show', pool %></td>
        <td><%= link_to 'Edit', edit_pool_path(pool) %></td>
        <td><%= link_to 'Destroy', pool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
       
        <td colspan="4">
          <ul>
          <% pool.questions.each do |question| %>
          <li>
            <%= question.content  %> <%= link_to 'Редактировать', edit_question_path(question) %>
          </li>   
           <% end %> 
         </ul>


        </td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pool', new_pool_path %>

app/views/pools/new.html.erb
<h1>New pool</h1>

<%= render 'form' %>

<%= link_to 'Back', pools_path %>

app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pool.name %>
</p>

<%= link_to 'Edit', edit_pool_path(@pool) %> |
<%= link_to 'Back', pools_path %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  

   <h3>Пулы</h3>

  <% if !@pools.nil? %>
  <% @pools.each do |pool| %>
    <%= label_tag(pool.id, pool.name, class: 'checkbox') do %>
      <%= check_box_tag('pool[]', pool.id, !QuestionPool.find_by(question_id: @question.id, pool_id: pool.id).nil?) %>
      <%= pool.name %>
    <% end %>
    
  <% end %>
  <% end %>

  <h3>Варианты ответов</h3>
  <% if !@options.nil? %>
    <% @options.each do |option| %>
    <%= label_tag(option.id, option.text, class: 'checkbox') do %>
      <%= check_box_tag('option[]', option.id, Option.find(option.id).correct ) %>
        <%= option.text %>
      <% end %>
    <% end %>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Список вопросов</h1>

<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><span class="badge badge-info"><%= question.id %></span> <%= question.content %>
          <% if question.pools.any? %>
 </br></br>
              <% question.pools.each do |pool| %>
                <span class="label"><%= pool.name %></span>
              <% end %>
 
          <% end %>
        </td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question), class: "btn btn-mini"  %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-mini" %></td>
      </tr>

       <tr>
       
        <td colspan="4">
          <ul class="unstyled">
            <% question.options.each do |option| %>
              <li class="strong">
                
                <%= link_to raw('<i class="icon-pencil"></i>'), edit_option_path(option) , class: "btn btn-mini" %>
                <%= raw('<a href="#" class="btn btn-success btn-mini disabled"><i class="icon-white icon-ok"></i></a>') if option.correct %>
                <%= option.text %>
                
              </li>   
            <% end %> 
          </ul>
        </td>
        
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый вопрос', new_question_path %>
<%= link_to 'Список пулов', pools_path %>
<%= link_to 'Список вариантов', options_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<% if @question.pools.any? %>
<p>
  <strong>Pools:</strong>
  <ul>
  <% @question.pools.each do |pool| %>
  <li><%= pool.name %></li>
  <% end %>
</ul>
</p>

<% end %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/static_pages/home.html.erb
 <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Тестирование</h1>
        <p>Тут у нас будет веселою, а именно будет проходить тестирование системытестирования. Будем жечь тряпки. Смеяться.</p>
        <p><a href="#" class="btn btn-primary btn-large">Пока не работает &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row-fluid">
        <div class="span4">
          <h2>Вопросы</h2>
          <p>Вопросы можно создавать, удалять и вообще они главное что есть. </p>
          <p><%= link_to 'К вопросам', questions_path, class: "btn"  %></p>
        </div>
        <div class="span4">
          <h2>Ответы</h2>
          <p>К каждому ответу должны быть вопросы. Ну или крайне желательно чтобы они были. Вот тут то мы их и будем вносить. Весело и забавно. Ответы иногда бывают правильные.</p>
          <p><%= link_to 'К ответам', options_path, class: "btn"  %></p>
       	</div>
        <div class="span4">
          <h2>Пулы</h2>
          <p>Вопросы объеденины в пулы. В пуле может быть несколько вопросов, собственно как и сам вопрос может принадлежать к разным пулам.</p>
          <p><%= link_to 'К пулам', pools_path, class: "btn"  %></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Все очень секретно 2013</p>
      </footer>